# Generated by Django 5.1.7 on 2025-04-08 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyword',
            name='meaning',
            field=models.TextField(blank=True, null=True),
        ),
    ]
