# Generated by Django 5.1.7 on 2025-04-08 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0002_dailyword_meaning'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyword',
            name='audio',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyword',
            name='example',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyword',
            name='phonetic',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
