# Generated by Django 5.1.7 on 2025-04-13 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0005_quizscore_streak'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnedword',
            name='level',
            field=models.CharField(default='beginner', max_length=20),
        ),
    ]
